# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: oneWayOut's blog
email: cia120@163.com
favicon: /assets/img/avatar.jpg

description: > # this means to ignore newlines until "baseurl:"
  我喜欢开源软件，大自然，音乐等一切给我们自由和美丽的事物. 希望在此记录生活和学习点滴，分享一些有用的东西. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  oneWayOut

encoding: utf-8

# Build settings
markdown: kramdown
